export const CREATE_GAME_REQUEST = 'CREATE_GAME_REQUEST';
export const CREATE_GAME_REQUEST_ERROR = 'CREATE_GAME_REQUEST_ERROR'
export const CREATE_GAME_REQUEST_SUCCESS = 'CREATE_GAME_REQUEST_SUCCESS'

export const UPDATE_GAME_REQUEST = 'UPDATE_GAME_REQUEST';
export const UPDATE_GAME_REQUEST_ERROR = 'UPDATE_GAME_REQUEST_ERROR'
export const UPDATE_GAME_REQUEST_SUCCESS = 'UPDATE_GAME_REQUEST_SUCCESS';

export const DELETE_GAME_REQUEST = 'DELETE_GAME_REQUEST'
export const DELETE_GAME_REQUEST_ERROR = 'DELETE_GAME_REQUEST_ERROR'
export const DELETE_GAME_REQUEST_SUCCESS = 'DELETE_GAME_REQUEST_SUCCESS'

export const GET_GAME_REQUEST = 'GET_GAME_REQUEST'
export const GET_GAME_REQUEST_ERROR = 'GET_GAME_REQUEST_ERROR'
export const GET_GAME_REQUEST_SUCCESS = 'GET_GAME_REQUEST_SUCCESS'

export const GET_ALL_GAMES_REQUEST = 'GET_ALL_GAMES_REQUEST'
export const GET_ALL_GAMES_REQUEST_ERROR = 'GET_ALL_GAMES_REQUEST_ERROR'
export const GET_ALL_GAMES_REQUEST_SUCCESS = 'GET_ALL_GAMES_REQUEST_SUCCESS'

export const GET_GAMES_REQUEST = 'GET_GAMES_REQUEST'
export const GET_GAMES_REQUEST_ERROR = 'GET_GAMES_REQUEST_ERROR'
export const GET_GAMES_REQUEST_SUCCESS = 'GET_GAMES_REQUEST_SUCCESS'

export const FORMAT_GAME_REQUEST = 'FORMAT_GAME_REQUEST';

export const START_GAME_REQUEST = 'START_GAME_REQUEST';
export const START_GAME_REQUEST_ERROR = 'START_GAME_REQUEST_ERROR';

export const GAME_START_INIT = 'GAME_START_INIT';


