export const CREATE_ROOM_REQUEST = 'CREATE_ROOM_REQUEST';
export const CREATE_ROOM_REQUEST_ERROR = 'CREATE_ROOM_REQUEST_ERROR'
export const CREATE_ROOM_REQUEST_SUCCESS = 'CREATE_ROOM_REQUEST_SUCCESS'

export const UPDATE_ROOM_REQUEST = 'UPDATE_ROOM_REQUEST';
export const UPDATE_ROOM_REQUEST_ERROR = 'UPDATE_ROOM_REQUEST_ERROR'
export const UPDATE_ROOM_REQUEST_SUCCESS = 'UPDATE_ROOM_REQUEST_SUCCESS';

export const DELETE_ROOM_REQUEST = 'DELETE_ROOM_REQUEST'
export const DELETE_ROOM_REQUEST_ERROR = 'DELETE_ROOM_REQUEST_ERROR'
export const DELETE_ROOM_REQUEST_SUCCESS = 'DELETE_ROOM_REQUEST_SUCCESS'

export const GET_ROOM_REQUEST = 'GET_ROOM_REQUEST'
export const GET_ROOM_REQUEST_ERROR = 'GET_ROOM_REQUEST_ERROR'
export const GET_ROOM_REQUEST_SUCCESS = 'GET_ROOM_REQUEST_SUCCESS'
