export const GIVE_SCORE_REQUEST = "GIVE_SCORE_REQUEST";
export const GIVE_SCORE_REQUEST_ERROR = "GIVE_SCORE_REQUEST_ERROR";
export const GIVE_SCORE_REQUEST_SUCCESS = "GIVE_SCORE_REQUEST_SUCCESS";
export const GET_SCORES_REQUEST = "GET_SCORES_REQUEST";
export const GET_SCORES_REQUEST_ERROR = "GET_SCORES_REQUEST_ERROR";
export const GET_SCORES_REQUEST_SUCCESS = "GET_SCORES_REQUEST_SUCCESS";
